Repository osushi-academy/sushi-chat, pull requests merged in 2021-06, with the labels that each got.

#227 停止ボタンが動作しないバグを修正
  app/front/components/SettingPage.vue
  server/src/models/room.ts
Labels: front, main

#230 複数管理者に対応
  app/front/components/SettingPage.vue
  app/front/pages/index.vue
Labels: front, main

#233 アプリケーションとNginxのログをcloudwatch logsに書き込むようにした
  server/src/database/database.ts
  terraform/.gitignore
  terraform/cloud_watch_logs.tf
  terraform/ec2.tf
  terraform/lb.tf
  terraform/rds.tf
  terraform/user_data.tpl
  terraform/variables.tf
Labels: main

#236 wsパッケージのバージョンをあげた
  server/package-lock.json
Labels: main

#235 スタンプをDBに保存するようにした。
  .idea/dataSources.xml
  .idea/sqldialects.xml
  server/src/database/database.ts
  server/src/database/ini.sql
  server/src/ioServer.ts
  server/src/models/room.ts
  server/src/stamp.ts
Labels: main, server

#224 [fix] 選択できるテキストの変更、URLに対応
  app/front/assets/scss/common.scss
  app/front/assets/scss/heart.scss
  app/front/assets/scss/index.scss
  app/front/components/Message.vue
  app/front/components/UrlToLink.vue
  app/front/layouts/default.vue
  app/front/nuxt.config.js
  app/front/pages/index.vue
Labels: main

#239 スクロールの挙動を修正
  app/front/assets/scss/index.scss
  app/front/components/ChatRoom.vue
  app/front/package.json
  app/front/yarn.lock
  package-lock.json
  package.json
Labels: main

#237 盛り上がりグラフを開閉可能にした
  app/front/assets/scss/index.scss
  app/front/components/AnalysisGraph.vue
  app/front/components/ChatRoom.vue
Labels: main

#247 [fix] 文字数制限の表示を変更
  app/front/assets/scss/index.scss
  app/front/components/TextArea.vue
Labels: main

#244 [fix]ホバー時にコメント数が見えないように
  app/front/components/AnalysisGraph.vue
Labels: main

#245 [fix]先頭と末尾の空白、改行を削除
  app/front/components/TextArea.vue
Labels: main

#246 [fix] set word-break
  app/front/components/UrlToLink.vue
Labels: main

#248 UI周りの修正
  app/front/assets/scss/index.scss
  app/front/components/Message.vue
Labels: main

#249 スクロール可能要素がダブってるのを修正
  app/front/assets/scss/index.scss
Labels: main

#234 Socket.io Admin UIというモニタリングツールを導入した
  server/package-lock.json
  server/package.json
  server/src/__test__/chat.ts
  server/src/ioServer.ts
  server/src/utils/crypt.ts
Labels: main

#257 OS情報のVuex移行
  app/front/components/ChatRoom.vue
  app/front/components/KeyInstruction.vue
  app/front/components/TextArea.vue
  app/front/pages/index.vue
  app/front/store/device.ts
  app/front/utils/store-accessor.ts
Labels: develop

#258 ユーザー情報のVuex移行
  app/front/components/ChatRoom.vue
  app/front/components/SelectIconModal.vue
  app/front/components/SettingPage.vue
  app/front/components/TextArea.vue
  app/front/components/TopicHeader.vue
  app/front/pages/index.vue
  app/front/store/userItems.ts
  app/front/utils/store-accessor.ts
Labels: develop
