Repository osushi-academy/sushi-chat, pull requests merged in 2021-09, with the labels that each got.

#329 アーキテクチャを導入したブランチをdevelopに合流
  app/server/src/__test__/chat.ts
  app/server/src/app.ts
  app/server/src/chatItem.ts
  app/server/src/database/database.ts
  app/server/src/database/ini.sql
  app/server/src/domain/chatItem/Answer.ts
  app/server/src/domain/chatItem/ChatItem.ts
  app/server/src/domain/chatItem/IChatItemDelivery.ts
  app/server/src/domain/chatItem/IChatItemRepository.ts
  app/server/src/domain/chatItem/Message.ts
  app/server/src/domain/chatItem/Question.ts
  app/server/src/domain/chatItem/Reaction.ts
  app/server/src/domain/room/IRoomDelivery.ts
  app/server/src/domain/room/IRoomRepository.ts
  app/server/src/domain/room/Room.ts
  app/server/src/domain/room/Topic.ts
  app/server/src/domain/stamp/IStampDelivery.ts
  app/server/src/domain/stamp/IStampRepository.ts
  app/server/src/domain/stamp/Stamp.ts
  app/server/src/domain/user/IUserDelivery.ts
  app/server/src/domain/user/IUserRepository.ts
  app/server/src/domain/user/User.ts
  app/server/src/events.ts
  app/server/src/infra/delivery/chatItem/ChatItemDelivery.ts
  app/server/src/infra/delivery/room/RoomDelivery.ts
  app/server/src/infra/delivery/stamp/EphemeralStampDelivery.ts
  app/server/src/infra/delivery/stamp/StampDelivery.ts
  app/server/src/infra/delivery/user/UserDelivery.ts
  app/server/src/infra/factory/PGClientFactory.ts
  app/server/src/infra/repository/User/EphemeralUserRepository.ts
  app/server/src/infra/repository/User/LocalMemoryUserRepository.ts
  app/server/src/infra/repository/chatItem/ChatItemRepository.ts
  app/server/src/infra/repository/chatItem/EphemeralChatItemRepository.ts
  app/server/src/infra/repository/room/EphemeralRoomRepository.ts
  app/server/src/infra/repository/room/RoomRepository.ts
  app/server/src/infra/repository/stamp/EphemeralStampRepository.ts
  app/server/src/infra/repository/stamp/StampRepository.ts
  app/server/src/ioServer.ts
  app/server/src/models/room.ts
  app/server/src/room.ts
  app/server/src/saveChatItem.ts
  app/server/src/serverSocket.ts
  app/server/src/service/chatItem/ChatItemResponseBuilder.ts
  app/server/src/service/chatItem/ChatItemService.ts
  app/server/src/service/chatItem/commands.ts
  app/server/src/service/room/RoomService.ts
  app/server/src/service/room/commands.ts
  app/server/src/service/stamp/StampService.ts
  app/server/src/service/stamp/commands.ts
  app/server/src/service/user/UserService.ts
  app/server/src/service/user/commands.ts
  app/server/src/stamp.ts
  app/server/src/topic.ts
Labels: server, develop

#340 Updated READMEs
  README.md
  app/server/README.md
Labels: server, develop

#349 ピン留めメッセージ追加に伴うAPI Spec修正
  doc/reference/sushi-chat-api.yaml
Labels: develop

#337 サーバーを複数台構成にし、masterブランチの更新時に自動デプロイするようにした
  .github/workflows/deploy-aws.yml
  .github/workflows/deploy-heroku.yml
  app/front/utils/socketIO.ts
  app/server/package.json
  app/server/src/ioServer.ts
  appspec.yml
  scripts/build_app.sh
  scripts/install_dependencies.sh
  scripts/mod_permission.sh
  scripts/start_app.sh
  scripts/stop_app.sh
  terraform/.gitignore
  terraform/deploy.tf
  terraform/ec2.tf
  terraform/output.tf
  terraform/redis.tf
  yarn.lock
Labels: server, develop

#365 Revert "サーバーを複数台構成にし、mainブランチの更新時に自動デプロイするようにした"
  .github/workflows/deploy-aws.yml
  .github/workflows/deployServer.yml
  app/front/utils/socketIO.ts
  app/server/package.json
  app/server/src/ioServer.ts
  appspec.yml
  scripts/build_app.sh
  scripts/install_dependencies.sh
  scripts/mod_permission.sh
  scripts/start_app.sh
  scripts/stop_app.sh
  terraform/.gitignore
  terraform/deploy.tf
  terraform/ec2.tf
  terraform/output.tf
  terraform/redis.tf
  yarn.lock
Labels: develop

#334 CIを作成してGitHub Actionsで実行するようにした
  .github/workflows/ci.yaml
  .prettierrc
  app/front/.eslintrc.js
  app/front/components/AnalysisGraph.vue
  app/front/components/ChatRoom.vue
  app/front/components/FavoriteButton.vue
  app/front/components/Message.vue
  app/front/components/SettingPage.vue
  app/front/components/TextArea.vue
  app/front/components/TopicHeader.vue
  app/front/models/contents.ts
  app/front/package.json
  app/front/pages/index.vue
  app/front/store/chatItems.ts
  app/front/store/topicStateItems.ts
  app/front/utils/ChartLine.ts
  app/front/utils/icons.ts
  app/front/utils/store-accessor.ts
  app/server/package.json
  app/server/src/__test__/chat.ts
  app/server/src/app.ts
  app/server/src/infra/factory/PGClientFactory.ts
  app/server/src/infra/repository/PGPool.ts
  app/server/src/infra/repository/chatItem/ChatItemRepository.ts
  app/server/src/infra/repository/room/RoomRepository.ts
  app/server/src/infra/repository/stamp/StampRepository.ts
  app/server/src/ioServer.ts
  app/server/src/service/room/RoomService.ts
  app/server/src/service/user/UserService.ts
  app/shared/package.json
  package.json
Labels: server, develop

#364 API定義を修正
  doc/reference/sushi-chat-api.yaml
Labels: develop

#371 [再]複数台サーバーの構成にした
  .github/workflows/deploy-aws.yml
  .github/workflows/deploy-heroku.yml
  app/front/utils/socketIO.ts
  app/server/README.md
  app/server/package.json
  app/server/src/ioServer.ts
  appspec.yml
  scripts/build_app.sh
  scripts/install_dependencies.sh
  scripts/mod_permission.sh
  scripts/start_app.sh
  scripts/stop_app.sh
  terraform/.gitignore
  terraform/deploy.tf
  terraform/ec2.tf
  terraform/output.tf
  terraform/redis.tf
  yarn.lock
Labels: server, develop

#336 Application Serviceクラスのユニットテストの作成
  app/server/src/__test__/chatItemServiceTest.ts
  app/server/src/__test__/roomServiceTest.ts
  app/server/src/__test__/stampServiceTest.ts
  app/server/src/domain/room/Topic.ts
  app/server/src/infra/delivery/chatItem/EphemeralChatItemDelivery.ts
  app/server/src/infra/delivery/room/EphemeralRoomDelivery.ts
  app/server/src/infra/delivery/stamp/EphemeralStampDelivery.ts
  app/server/src/infra/delivery/user/EphemeralUserDelivery.ts
Labels: server, develop

#359 Created new DB schema
  doc/ER/ER_concept.drawio
  doc/ER/ER_concept.png
  doc/ER/ER_logic.png
  doc/ER/ER_logic.puml
Labels: server, develop

#368 API Specを型定義に落とす
  app/shared/src/index.ts
  app/shared/src/types/event.ts
  app/shared/src/types/model.ts
  app/shared/src/types/models.ts
  app/shared/src/types/responseBuilder.ts
  app/shared/src/types/rest.ts
  app/shared/src/types/socketio.ts
  app/shared/src/types/userInputActions.ts
  app/shared/src/types/utils.ts
  app/shared/tsconfig.json
  doc/reference/sushi-chat-api.yaml
Labels: develop

#375 updated postgres engin version
  terraform/rds.tf
Labels: develop

#380 API Specデグレを修正
  doc/reference/sushi-chat-api.yaml
Labels: develop

#363 サーバーサイドのコードのリファクタ
  app/server/src/__test__/chat.ts
  app/server/src/__test__/chatItemServiceTest.ts
  app/server/src/__test__/roomServiceTest.ts
  app/server/src/__test__/stampServiceTest.ts
  app/server/src/app.ts
  app/server/src/domain/chatItem/Answer.ts
  app/server/src/domain/chatItem/ChatItem.ts
  app/server/src/domain/chatItem/Message.ts
  app/server/src/domain/chatItem/Question.ts
  app/server/src/domain/chatItem/Reaction.ts
  app/server/src/domain/room/IRoomFactory.ts
  app/server/src/domain/room/Room.ts
  app/server/src/domain/stamp/IStampDelivery.ts
  app/server/src/domain/user/IconId.ts
  app/server/src/domain/user/User.ts
  app/server/src/infra/delivery/stamp/EphemeralStampDelivery.ts
  app/server/src/infra/delivery/stamp/StampDelivery.ts
  app/server/src/infra/factory/RoomFactory.ts
  app/server/src/infra/repository/User/LocalMemoryUserRepository.ts
  app/server/src/ioServer.ts
  app/server/src/service/chatItem/ChatItemResponseBuilder.ts
  app/server/src/service/chatItem/ChatItemService.ts
  app/server/src/service/room/RoomService.ts
  app/server/src/service/room/commands.ts
  app/server/src/service/user/UserService.ts
Labels: develop

#383 API定義を修正
  doc/reference/sushi-chat-api.yaml
Labels: develop

#369 Socket.IOとexpressに型定義を追加
  .github/workflows/ci.yaml
  app/server/src/app.ts
  app/server/src/expressRoute.ts
  app/server/src/ioServer.ts
  app/shared/package.json
  app/shared/src/types/rest.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: develop

#379 認証周りを実装
  app/front/middleware/loginComplete.ts
  app/front/middleware/privateRoute.ts
  app/front/nuxt.config.js
  app/front/package.json
  app/front/pages/login.vue
  app/front/pages/profile.vue
  app/front/store/auth.ts
  app/front/tsconfig.json
  app/front/utils/store-accessor.ts
  app/server/.env.example
  app/server/package.json
  app/server/src/app.ts
  app/server/src/utils/auth.ts
  app/server/src/utils/initFirebase.ts
  yarn.lock
Labels: develop

#385 API定義を修正
  doc/reference/sushi-chat-api.yaml
Labels: develop

#317 developのスタンプエラー修正とvuex移行
  .gitignore
  app/front/components/AnalysisGraph.vue
  app/front/components/ChatRoom.vue
  app/front/components/FavoriteButton.vue
  app/front/components/FavoriteEffectItem.vue
  app/front/components/Message.vue
  app/front/components/TextArea.vue
  app/front/pages/index.vue
  app/front/store/stamps.ts
  app/front/utils/store-accessor.ts
  app/front/utils/waitedLoop.ts
Labels: develop

#393 updated deploy process
  package.json
  scripts/build_app.sh
  scripts/install_dependencies.sh
Labels: server, develop

#394 admin's managedRoomIds is not null
  app/server/src/domain/admin/IAdminRepository.ts
  app/server/src/domain/admin/admin.ts
  app/server/src/infra/repository/admin/AdminRepository.ts
Labels: server

#398 revert topicheader
  app/front/components/TopicHeader.vue
  app/front/pages/index.vue
Labels: develop

#370 APIクライアントを実装
  README.md
  app/front/apiClient/index.ts
  app/front/nuxt.config.js
  app/front/plugins/apiClient.ts
Labels: develop

#402 [fix]OGPのURL
  app/front/components/Home/CreationCompletedModal.vue
  app/front/nuxt.config.js
Labels: develop

#403 removed duplicating initialize firabase
  app/server/src/app.ts
  app/server/src/utils/auth.ts
  app/server/src/utils/initFirebase.ts
Labels: bug, server, develop

#407 develop-uI -> develop
  app/front/components/ChatRoom.vue
  app/front/components/Message.vue
  app/front/components/TopicHeader.vue
Labels: develop

#409 寿司選択画面UI
  app/front/assets/scss/app.scss
  app/front/assets/scss/home/variables.scss
  app/front/assets/scss/modal.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/NotFound.vue
  app/front/components/NotStarted.vue
  app/front/components/SelectIconModal.vue
  app/front/pages/index.vue
  app/front/store/userItems.ts
Labels: develop

#405 yarn startの修正
  .github/workflows/ci.yaml
  .github/workflows/deploy-aws.yml
  app/server/package.json
  package.json
  scripts/start_app.sh
  terraform/ec2.tf
  terraform/lb.tf
  terraform/rds.tf
  terraform/route53.tf
  terraform/variables.tf
Labels: develop

#415 ルーム作成 API繋ぎ込み
  app/front/components/Home/CreationCompletedModal.vue
  app/front/pages/room/create.vue
  app/server/src/rest.ts
  app/shared/src/types/rest.ts
Labels: develop

#414 [socket] ユーザーの入室
  app/front/components/AdminTool/AdminTool.vue
  app/front/pages/index.vue
  doc/reference/sushi-chat-api.yaml
Labels: develop

#416 leaveroomでなぜかエラーが発生する
  app/server/src/service/user/UserService.ts
Labels: develop

#421 寿司選択画面に情報を追加
  app/front/assets/scss/common.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/SelectIconModal.vue
Labels: develop

#423 [fix]ルーム登録画面のスマホレイアウト崩れ
  app/front/assets/scss/home/home.scss
  app/front/assets/scss/home/variables.scss
Labels: develop

#426 hotfix/tomokon
  app/server/src/app.ts
  app/server/src/database/ini.sql
  app/server/src/domain/admin/IAdminAuth.ts
  app/server/src/domain/admin/IAdminRepository.ts
  app/server/src/domain/admin/admin.ts
  app/server/src/domain/room/IRoomFactory.ts
  app/server/src/domain/room/Room.ts
  app/server/src/infra/auth/AdminAuth.ts
  app/server/src/infra/factory/RoomFactory.ts
  app/server/src/infra/repository/User/UserRepository.ts
  app/server/src/infra/repository/admin/AdminRepository.ts
  app/server/src/infra/repository/room/RoomRepository.ts
  app/server/src/rest.ts
  app/server/src/service/admin/AdminService.ts
  app/server/src/service/room/RestRoomService.ts
  app/server/src/service/room/commands.ts
  app/server/src/service/user/UserService.ts
  doc/ER/ER_logic.png
  doc/ER/ER_logic.puml
Labels: server, develop

#420 room/id topic
  app/server/src/app.ts
  app/server/src/domain/room/Room.ts
  app/server/src/rest.ts
  app/server/src/service/room/RestRoomService.ts
  app/server/src/types/utils.ts
  app/server/src/utils/topics.ts
  app/shared/src/types/models.ts
  app/shared/src/types/rest.ts
Labels: develop

#434 初回定型分UI
  app/front/assets/scss/index.scss
  app/front/components/FixedPhrase.vue
  app/front/components/TextArea.vue
Labels: develop

#431 ヘッダー3点リーダ内のUI
  app/front/assets/scss/app.scss
  app/front/assets/scss/index.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/TopicHeader.vue
Labels: develop

#433 Nagata/UI/addtopics
  app/front/assets/scss/home/home.scss
  app/front/components/Home/AddSessionsModal.vue
  app/front/components/Home/CreationCompletedModal.vue
  app/front/components/Home/Modal.vue
  app/front/pages/room/create.vue
Labels: develop

#430 ENTER_ROOM でのユーザー作成処理のバグ修正
  app/server/src/infra/repository/User/UserRepository.ts
  app/server/src/service/user/UserService.ts
Labels: server, develop

#428 マイページ繋ぎ込み
  app/front/apiClient/index.ts
  app/front/assets/scss/home/home.scss
  app/front/assets/scss/home/variables.scss
  app/front/pages/home.vue
  app/server/src/service/room/RestRoomService.ts
Labels: develop

#435 API呼び出し時にトークンがセットされる実装
  app/front/apiClient/index.ts
  app/front/assets/scss/home/variables.scss
  app/front/pages/home.vue
  app/front/pages/login.vue
  app/front/pages/profile.vue
  app/front/plugins/apiClient.ts
  app/front/store/auth.ts
Labels: develop

#438 build room の修正
  app/server/src/service/room/RestRoomService.ts
Labels: develop

#442 マイページにログイン中のアカウントを表示する
  app/front/pages/home.vue
Labels: develop

#429 inviteAdmin時にrooms_adminsテーブルに関連レコードを登録するようにした
  app/server/src/infra/repository/room/RoomRepository.ts
  app/server/src/ioServer.ts
  app/server/src/rest.ts
  app/server/src/service/admin/AdminService.ts
  app/server/src/service/chatItem/ChatItemService.ts
  app/server/src/service/room/RealtimeRoomService.ts
  app/server/src/service/room/RestRoomService.ts
  app/server/src/service/stamp/StampService.ts
  app/server/src/service/user/UserService.ts
Labels: server, develop

#439 ルーム開始
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/NotStarted.vue
  app/front/components/SelectIconModal.vue
  app/front/pages/index.vue
Labels: develop

#436 get room/:id / Topic, TopicStateの型をsharedに合わせた
  app/front/assets/scss/admin.scss
  app/front/assets/scss/common.scss
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/AnalysisGraph.vue
  app/front/components/ChatRoom.vue
  app/front/components/CreateRoomModal.vue
  app/front/components/SelectIconModal.vue
  app/front/components/Sidebar/SidebarDrawer.vue
  app/front/components/TextArea.vue
  app/front/components/TopicHeader.vue
  app/front/pages/index.vue
  app/front/pages/room/create.vue
  app/front/store/topicStateItems.ts
  app/front/store/topics.ts
Labels: develop

#444 socketにidToken渡した
  app/front/components/FavoriteButton.vue
  app/front/pages/index.vue
  app/front/store/chatItems.ts
  app/front/store/stamps.ts
  app/front/utils/socketIO.ts
Labels: develop

#448 LP作成
  app/front/assets/img/LP_background.png
  app/front/assets/img/LP_pc_and_sp.png
  app/front/assets/img/twitter.jpeg
  app/front/assets/scss/app.scss
  app/front/assets/scss/lp.scss
  app/front/pages/login.vue
Labels: develop

#450 LP修正
  app/front/assets/scss/lp.scss
  app/front/pages/login.vue
Labels: develop

#449 TopicStateの変更
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/ChatRoom.vue
  app/front/components/NotStarted.vue
  app/front/components/SelectIconModal.vue
  app/front/components/TopicHeader.vue
  app/front/pages/home.vue
  app/front/pages/index.vue
  app/front/store/topicStateItems.ts
  app/front/utils/socketIO.ts
  app/server/src/database/ini.sql
  app/server/src/domain/chatItem/Answer.ts
  app/server/src/domain/chatItem/ChatItem.ts
  app/server/src/domain/chatItem/Message.ts
  app/server/src/domain/chatItem/Question.ts
  app/server/src/domain/chatItem/Reaction.ts
  app/server/src/domain/room/Room.ts
  app/server/src/domain/user/IUserFactory.ts
  app/server/src/domain/user/SystemUser.ts
  app/server/src/domain/user/User.ts
  app/server/src/infra/delivery/chatItem/ChatItemDelivery.ts
  app/server/src/infra/factory/UserFactory.ts
  app/server/src/infra/repository/User/UserRepository.ts
  app/server/src/infra/repository/chatItem/ChatItemRepository.ts
  app/server/src/infra/repository/chatItem/EphemeralChatItemRepository.ts
  app/server/src/infra/repository/room/RoomRepository.ts
  app/server/src/rest.ts
  app/server/src/service/chatItem/ChatItemModelBuilder.ts
  app/server/src/service/chatItem/ChatItemService.ts
  app/server/src/service/user/UserService.ts
Labels: develop

#443 RealTimeRoomServiceのテスト作成
  .github/workflows/ci.yaml
  app/server/src/__test__/chat.ts
  app/server/src/__test__/chatItemServiceTest.ts
  app/server/src/__test__/roomServiceTest.ts
  app/server/src/__test__/stampServiceTest.ts
  app/server/src/__test__/testRealTimeRoomService.ts
  app/server/src/domain/room/Room.ts
  app/server/src/infra/delivery/room/EphemeralRoomDelivery.ts
  app/server/src/service/room/RealtimeRoomService.ts
Labels: server, develop

#451 create AdminService test
  app/server/src/__test__/testAdminService.ts
  app/server/src/__test__/testRealTimeRoomService.ts
  app/server/src/__test__/testRestRoomService.ts
  app/server/src/__test__/testUserService.ts
  app/server/src/infra/repository/admin/EphemeralAdminRepository.ts
  app/server/src/infra/repository/room/EphemeralRoomRepository.ts
Labels: server, develop

#468 update logging
  app/server/src/ioServer.ts
  app/server/src/rest.ts
Labels: server, develop

#471 管理者ツールURLコピー完了アニメーション
  app/front/components/AdminTool/AdminTool.vue
Labels: develop

#453 [socket]ChatItem
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/AnalysisGraph.vue
  app/front/components/ChatRoom.vue
  app/front/components/FavoriteButton.vue
  app/front/components/Message.vue
  app/front/components/SelectIconModal.vue
  app/front/components/Sidebar/SidebarContent.vue
  app/front/components/TextArea.vue
  app/front/nuxt.config.js
  app/front/pages/home.vue
  app/front/pages/index.vue
  app/front/plugins/socket.ts
  app/front/store/chatItems.ts
  app/front/store/stamps.ts
  app/front/utils/socketIO.ts
  app/server/src/infra/repository/chatItem/ChatItemRepository.ts
  app/server/src/ioServer.ts
Labels: develop

#470 chatItem絞り込み
  app/front/components/ChatRoom.vue
  app/front/components/TopicHeader.vue
Labels: develop

#472 寿司選択画面のスタイル調整
  app/front/assets/scss/sushiselect.scss
  app/front/components/NotFound.vue
  app/front/components/NotStarted.vue
  app/front/components/SelectIconModal.vue
Labels: develop

#474 fix deploy start app command
  scripts/start_app.sh
Labels: main

#476 LPのスタイル崩れを修正
  app/front/assets/scss/lp.scss
Labels: develop

#456 ピン留め
  app/front/assets/scss/index.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/ChatRoom.vue
  app/front/components/Message.vue
  app/front/components/TopicHeader.vue
  app/front/store/pinnedChatItems.ts
  app/front/utils/store-accessor.ts
Labels: develop

#479 retrieve system user on RoomRepository.find()
  app/server/src/infra/repository/room/RoomRepository.ts
Labels: bug, server, main

#483 fix deploy configuration
  scripts/start_app.sh
  scripts/stop_app.sh
  terraform/deploy.tf
Labels: bug, main

#489 roomIdクエリがない場合/loginにリダイレクト
  app/front/pages/index.vue
Labels: develop

#486 Tomokon/hotfix/reaction to answer
  app/server/src/infra/repository/chatItem/ChatItemRepository.ts
  app/server/src/ioServer.ts
  app/server/src/service/chatItem/ChatItemModelBuilder.ts
Labels: bug, server, main

#493 fiix seed topic states
  app/server/src/database/seed/topic_states.sql
Labels: bug, server, main

#482 main <- develop
  app/front/assets/scss/index.scss
  app/front/assets/scss/lp.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/ChatRoom.vue
  app/front/components/FavoriteButton.vue
  app/front/components/Message.vue
  app/front/components/TopicHeader.vue
  app/front/pages/index.vue
  app/front/store/pinnedChatItems.ts
  app/front/store/stamps.ts
  app/front/utils/store-accessor.ts
Labels: main

#498 [fix]ヘッダーとテキストエリアでindex違う
  app/front/components/ChatRoom.vue
Labels: develop

#496 [fix]質問投稿時にcmd+enterが効かない
  app/front/assets/scss/admin.scss
  app/front/components/TextArea.vue
Labels: main, develop

#501 senderTypeの出しわけ
  app/front/assets/scss/index.scss
  app/front/components/ChatRoom.vue
  app/front/components/Message.vue
  app/front/components/SelectIconModal.vue
  app/front/components/TextArea.vue
  app/front/pages/index.vue
  app/front/store/userItems.ts
Labels: main

#502 fix IconId validation to ues shari
  app/server/src/domain/user/IconId.ts
Labels: bug, server, main

#503 textareaの高さ合わせた
  app/front/assets/scss/index.scss
  app/front/components/Message.vue
  app/front/components/TextArea.vue
Labels: main, develop

#522 Fix/yuta ike/fix bugs
  app/front/assets/scss/admin.scss
  app/front/assets/scss/common.scss
  app/front/assets/scss/home/home.scss
  app/front/assets/scss/home/variables.scss
  app/front/assets/scss/variables.scss
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/ChatRoom.vue
  app/front/nuxt.config.js
  app/front/pages/home.vue
  app/front/pages/index.vue
  app/front/pages/room/create.vue
  app/front/utils/formatDate.ts
Labels: develop

#535 add architecture image
  doc/architecture/sushi_chat_architecture.drawio
  doc/architecture/sushi_chat_architecture.png
Labels: documentation, main

#536 not write error on client error
  app/server/src/rest.ts
Labels: server, main

#533 デザイン修正2
  app/front/assets/scss/admin.scss
  app/front/assets/scss/common.scss
  app/front/assets/scss/home/home.scss
  app/front/assets/scss/home/variables.scss
  app/front/assets/scss/index.scss
  app/front/assets/scss/sushiselect.scss
  app/front/components/ChatRoom.vue
  app/front/components/FavoriteButton.vue
  app/front/components/Home/CreationCompletedModal.vue
  app/front/components/Home/InviteSuccess.vue
  app/front/components/Message.vue
  app/front/components/SelectIconModal.vue
  app/front/components/TextArea.vue
  app/front/components/TopicHeader.vue
  app/front/components/UrlToLink.vue
  app/front/nuxt.config.js
  app/front/package.json
  app/front/pages/home.vue
  app/front/pages/invited.vue
  app/front/pages/room/create.vue
  app/front/store/pinnedChatItems.ts
  yarn.lock
Labels: develop

#490 E2EテストのREST部分を作成
  app/server/package.json
  app/server/src/__test__/chat.ts
  app/server/src/utils/topics.ts
  yarn.lock
Labels: server, main

#547 トピック変更のsocket通知修正
  app/front/pages/index.vue
Labels: develop

#551 スタンプを一度しか押せないように変更
  app/front/assets/scss/index.scss
  app/front/components/AdminTool/AdminTool.vue
  app/front/components/Message.vue
  app/front/pages/index.vue
  app/front/pages/invited.vue
  app/front/pages/room/create.vue
  app/front/store/topicStateItems.ts
Labels: develop

#559 リプライ時にtextareaにフォーカスする
  app/front/components/ChatRoom.vue
  app/front/components/TextArea.vue
Labels: develop
